services:
  db:
    image: postgres:18-alpine@sha256:77f585114c32fbca283dc835b0596f4e52b51b4c6662d7810b2f4084f60a1873
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    ports:
      - ${SQL_PORT}:${SQL_PORT}
    restart: on-failure
    healthcheck:
      test: 'PGPASSWORD=${SQL_PASSWORD} pg_isready -h 127.0.0.1 -U ${SQL_USER} -d ${SQL_DATABASE}'

  redis:
    image: redis:8-alpine@sha256:3811787313eba226a2ef38658c6ccb91cd5e110edc89c37767de373120a0e5a0
    ports:
      - "6379:6379"
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/app/
      - /app/.venv
    command: uv run python eodhp_web_presence/manage.py migrate
    depends_on:
      db:
        condition: service_healthy

  web-presence:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/app/
      - /app/.venv
      - /app/eodhp_web_presence/dist
      # - /app/eodhp_web_presence/staticfiles
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  postgres_data:
