version: '3.8'
services:
  web:
    build:
      context: .
      args:
        NODE_ENV: development
        DEBUG: 1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
      - node_modules_volume:/app/node_modules
    env_file:
      - .env
    environment:
      - DJANGO_ENV=development
      - USE_S3=False
    depends_on:
      - webpack

  webpack:
    build:
      context: .
      args:
        NODE_ENV: development
        DEBUG: 0
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    command: bash -c 'npm install && npm start'
    entrypoint: ""

volumes:
  media_volume:
  node_modules_volume:
