# syntax=docker/dockerfile:1@sha256:4a43a54dd1fedceb30ba47e76cfcf2b47304f4161c0caeac2db1c61804ea3c91
FROM node:22-slim@sha256:813a7480f28fdadac1f7f5c824bcdad435b5bc1322a5968bbbdef8d058f9dff4 AS js_builder

WORKDIR /app

COPY package*.json .
RUN npm install

COPY assets ./assets
COPY scripts ./scripts
COPY webpack.config.js ./

RUN npm run build

FROM ghcr.io/astral-sh/uv:python3.13-trixie-slim@sha256:74ee1af27961f5fe73f70146808097ea11e03464cecaac33e60e173dc62e9202

WORKDIR /app

# Install build dependencies needed by libsass
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update --yes --quiet \
    && apt-get install --yes --quiet --no-install-recommends \
    build-essential

# Install dependencies (including dev)
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project

# Copy project files
COPY . /app

# Sync the project
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen

COPY --from=js_builder /app/eodhp_web_presence/dist/mdi_icons.json ./eodhp_web_presence/dist/mdi_icons.json
COPY --from=js_builder /app/eodhp_web_presence/staticfiles ./eodhp_web_presence/staticfiles
RUN uv run --no-sync python eodhp_web_presence/manage.py collectstatic --noinput

CMD ["uv", "run", "--no-sync", "python", "./eodhp_web_presence/manage.py", "runserver", "0.0.0.0:8000"]
