services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    env_file:
      - .env
    command: /usr/src/app/entrypoint.sh
    depends_on:
      - webpack
  webpack:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: /bin/sh -c "npm install && npm start"

volumes:
  media_volume:
