services:
  db:
    image: kartoza/postgis:latest@sha256:5c42c81bb6bbe4d42a4c1c87a98b4e3aaf9dca39fa3352047179552f4d622e5f
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${SQL_HOST}
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASS=${SQL_PASSWORD}
      - FORCE_SSL=TRUE
    ports:
      - ${SQL_PORT}:${SQL_PORT}
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=${SQL_PASSWORD} pg_isready -h 127.0.0.1 -U ${SQL_USER} -d ${SQL_DATABASE}"

  web-presence:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/app/
      - /app/.venv
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
