# syntax=docker/dockerfile:1@sha256:87999aa3d42bdc6bea60565083ee17e86d1f3339802f543c0d03998580f9cb89
FROM node:24-slim@sha256:6f7b03f7c2c8e2e784dcf9295400527b9b1270fd37b7e9a7285cf83b6951452d AS js_builder

WORKDIR /app

COPY package*.json .
RUN npm install

COPY assets ./assets
COPY scripts ./scripts
COPY webpack.config.js ./

RUN npm run build

FROM ghcr.io/astral-sh/uv:python3.13-trixie-slim@sha256:fb576a1ff0c6b967e8b466695af934e34161c4a99c2fbfb859261d4a24d4a8d3

WORKDIR /app

# Install build dependencies needed by libsass
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update --yes --quiet \
    && apt-get install --yes --quiet --no-install-recommends \
    build-essential

# Install dependencies (including dev)
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project

# Copy project files
COPY . /app

# Sync the project
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen

COPY --from=js_builder /app/eodhp_web_presence/dist/mdi_icons.json ./eodhp_web_presence/dist/mdi_icons.json
COPY --from=js_builder /app/eodhp_web_presence/staticfiles ./eodhp_web_presence/staticfiles
RUN uv run --no-sync python eodhp_web_presence/manage.py collectstatic --noinput

CMD ["uv", "run", "--no-sync", "python", "./eodhp_web_presence/manage.py", "runserver", "0.0.0.0:8000"]
