# Generated by Django 5.0.1 on 2024-02-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("help", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="helppage",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Date"),
        ),
    ]
