# Generated by Django 5.0.1 on 2024-02-06 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("help", "0002_helppage_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helpindexpage",
            name="date_published",
        ),
        migrations.RemoveField(
            model_name="helpindexpage",
            name="subtitle",
        ),
    ]
