# Generated by Django 5.0.9 on 2025-02-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericpage",
            name="back_button_location",
            field=models.CharField(
                blank=True,
                help_text="URL to redirect to when the back button is clicked",
                max_length=255,
            ),
        ),
    ]
