# Generated by Django 5.0.9 on 2025-02-14 09:14

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_genericpage_back_button_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericpage",
            name="topics",
            field=wagtail.fields.StreamField(
                [
                    (
                        "topic_panel",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title of the documentation panel", required=True
                                    ),
                                ),
                                (
                                    "slug",
                                    wagtail.blocks.CharBlock(
                                        help_text="Unique identifier in the url e.g. workflow",
                                        max_length=50,
                                        required=True,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="Description of the documentation panel",
                                        required=True,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Optional image for the documentation panel",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Add topic cards to nest additional pages.",
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "content_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional heading", required=False
                                    ),
                                ),
                                ("paragraph", wagtail.blocks.RichTextBlock(required=False)),
                                ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    ("blockquote", wagtail.blocks.BlockQuoteBlock()),
                    ("raw_html", wagtail.blocks.RawHTMLBlock()),
                    (
                        "code",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "language",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("bash", "Bash/Shell"),
                                            ("css", "CSS"),
                                            ("diff", "diff"),
                                            ("html", "HTML"),
                                            ("javascript", "Javascript"),
                                            ("json", "JSON"),
                                            ("python", "Python"),
                                            ("scss", "SCSS"),
                                            ("yaml", "YAML"),
                                        ],
                                        help_text="Coding language",
                                        identifier="language",
                                        label="Language",
                                    ),
                                ),
                                ("code", wagtail.blocks.TextBlock(identifier="code", label="Code")),
                            ],
                            label="Code",
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
