# Generated by Django 5.0.9 on 2025-01-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_casestudiespage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericpage',
            name='subtitle',
        ),
    ]
