# Generated by Django 6.0.3 on 2026-03-23 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_genericpage_topics_alter_genericpage_body"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="aim_1_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional internal page link for this card",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="aim_2_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional internal page link for this card",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="aim_3_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional internal page link for this card",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="aim_4_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional internal page link for this card",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
    ]
