# Generated by Django 5.0.9 on 2025-01-21 16:30

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_hero_text_homepage_overview_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='aim_1_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='aim_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='aims/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='aim_1_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='aim_2_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='aim_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='aims/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='aim_2_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='aim_3_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='aim_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='aims/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='aim_3_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='aim_4_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='aim_4_image',
            field=models.ImageField(blank=True, null=True, upload_to='aims/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='aim_4_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
