# Generated by Django 5.0.9 on 2025-01-21 16:38

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_aim_1_description_homepage_aim_1_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='aim_1_description',
            field=wagtail.fields.RichTextField(blank=True, default='Description of our first aim.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='aim_1_title',
            field=models.CharField(blank=True, default='Our First Aim', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='aim_2_description',
            field=wagtail.fields.RichTextField(blank=True, default='Description of our second aim.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='aim_2_title',
            field=models.CharField(blank=True, default='Our Second Aim', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='aim_3_description',
            field=wagtail.fields.RichTextField(blank=True, default='Description of our third aim.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='aim_3_title',
            field=models.CharField(blank=True, default='Our Third Aim', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='aim_4_description',
            field=wagtail.fields.RichTextField(blank=True, default='Description of our fourth aim.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='aim_4_title',
            field=models.CharField(blank=True, default='Our Fourth Aim', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='overview_text',
            field=wagtail.fields.RichTextField(blank=True, default='Welcome to our website!'),
        ),
    ]
