# Generated by Django 5.0.9 on 2025-01-29 15:43

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_documentationpage_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationpage',
            name='topics',
            field=wagtail.fields.StreamField([('documentation_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title of the documentation panel', required=True)), ('slug', wagtail.blocks.CharBlock(help_text='Unique identifier in the url e.g. workflow', max_length=50, required=True)), ('description', wagtail.blocks.RichTextBlock(help_text='Description of the documentation panel', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Optional image for the documentation panel', required=False))]))], blank=True, help_text='Add documentation panels to this page.', use_json_field=True),
        ),
    ]
