# Generated by Django 6.0.3 on 2026-03-23 15:12

import django.db.models.deletion
import wagtail.fields
import wagtailcache.cache
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_documentationpage_topics_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_block", 3), ("blockquote", 4), ("raw_html", 5), ("code", 8)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    3: ("wagtail.blocks.StructBlock", [[("heading", 0), ("paragraph", 1), ("image", 2)]], {}),
                    4: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    5: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    8: ("wagtail.blocks.StructBlock", [[("language", 6), ("code", 7)]], {"label": "Code"}),
                },
            ),
        ),
        migrations.AddField(
            model_name="aboutindexpage",
            name="hero_caption",
            field=models.CharField(blank=True, help_text="Caption or alt-text for the hero image", max_length=255),
        ),
        migrations.AddField(
            model_name="aboutindexpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Main hero or banner image for the top of the page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="aboutindexpage",
            name="topics",
            field=wagtail.fields.StreamField(
                [("topic_panel", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title of the documentation panel", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Unique identifier in the url e.g. workflow",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Description of the documentation panel", "required": True},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional image for the documentation panel", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "help_text": "Featured image", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("slug", 1), ("description", 2), ("image", 3), ("featured_image", 4)]],
                        {},
                    ),
                },
                help_text="Add topic cards to nest additional pages.",
            ),
        ),
        migrations.AddField(
            model_name="casestudiespage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_block", 3), ("blockquote", 4), ("raw_html", 5), ("code", 8)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    3: ("wagtail.blocks.StructBlock", [[("heading", 0), ("paragraph", 1), ("image", 2)]], {}),
                    4: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    5: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    8: ("wagtail.blocks.StructBlock", [[("language", 6), ("code", 7)]], {"label": "Code"}),
                },
            ),
        ),
        migrations.AddField(
            model_name="casestudiespage",
            name="hero_caption",
            field=models.CharField(blank=True, help_text="Caption or alt-text for the hero image", max_length=255),
        ),
        migrations.AddField(
            model_name="casestudiespage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Main hero or banner image for the top of the page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="casestudiespage",
            name="topics",
            field=wagtail.fields.StreamField(
                [("topic_panel", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title of the documentation panel", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Unique identifier in the url e.g. workflow",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Description of the documentation panel", "required": True},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional image for the documentation panel", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "help_text": "Featured image", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("slug", 1), ("description", 2), ("image", 3), ("featured_image", 4)]],
                        {},
                    ),
                },
                help_text="Add topic cards to nest additional pages.",
            ),
        ),
        migrations.AddField(
            model_name="dataindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_block", 3), ("blockquote", 4), ("raw_html", 5), ("code", 8)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    3: ("wagtail.blocks.StructBlock", [[("heading", 0), ("paragraph", 1), ("image", 2)]], {}),
                    4: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    5: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    8: ("wagtail.blocks.StructBlock", [[("language", 6), ("code", 7)]], {"label": "Code"}),
                },
            ),
        ),
        migrations.AddField(
            model_name="dataindexpage",
            name="hero_caption",
            field=models.CharField(blank=True, help_text="Caption or alt-text for the hero image", max_length=255),
        ),
        migrations.AddField(
            model_name="dataindexpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Main hero or banner image for the top of the page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="dataindexpage",
            name="topics",
            field=wagtail.fields.StreamField(
                [("topic_panel", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title of the documentation panel", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Unique identifier in the url e.g. workflow",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Description of the documentation panel", "required": True},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional image for the documentation panel", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "help_text": "Featured image", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("slug", 1), ("description", 2), ("image", 3), ("featured_image", 4)]],
                        {},
                    ),
                },
                help_text="Add topic cards to nest additional pages.",
            ),
        ),
        migrations.AddField(
            model_name="docsindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_block", 3), ("blockquote", 4), ("raw_html", 5), ("code", 8)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    3: ("wagtail.blocks.StructBlock", [[("heading", 0), ("paragraph", 1), ("image", 2)]], {}),
                    4: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    5: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    8: ("wagtail.blocks.StructBlock", [[("language", 6), ("code", 7)]], {"label": "Code"}),
                },
            ),
        ),
        migrations.AddField(
            model_name="docsindexpage",
            name="hero_caption",
            field=models.CharField(blank=True, help_text="Caption or alt-text for the hero image", max_length=255),
        ),
        migrations.AddField(
            model_name="docsindexpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Main hero or banner image for the top of the page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="docsindexpage",
            name="topics",
            field=wagtail.fields.StreamField(
                [("topic_panel", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title of the documentation panel", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Unique identifier in the url e.g. workflow",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Description of the documentation panel", "required": True},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional image for the documentation panel", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "help_text": "Featured image", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("slug", 1), ("description", 2), ("image", 3), ("featured_image", 4)]],
                        {},
                    ),
                },
                help_text="Add topic cards to nest additional pages.",
            ),
        ),
        migrations.AlterField(
            model_name="genericpage",
            name="intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.CreateModel(
            name="CatalogueIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_caption",
                    models.CharField(blank=True, help_text="Caption or alt-text for the hero image", max_length=255),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("content_block", 3), ("blockquote", 4), ("raw_html", 5), ("code", 8)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                            1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                            3: ("wagtail.blocks.StructBlock", [[("heading", 0), ("paragraph", 1), ("image", 2)]], {}),
                            4: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                            5: ("wagtail.blocks.RawHTMLBlock", (), {}),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("bash", "Bash/Shell"),
                                        ("css", "CSS"),
                                        ("diff", "diff"),
                                        ("html", "HTML"),
                                        ("javascript", "Javascript"),
                                        ("json", "JSON"),
                                        ("python", "Python"),
                                        ("scss", "SCSS"),
                                        ("yaml", "YAML"),
                                    ],
                                    "help_text": "Coding language",
                                    "identifier": "language",
                                    "label": "Language",
                                },
                            ),
                            7: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                            8: ("wagtail.blocks.StructBlock", [[("language", 6), ("code", 7)]], {"label": "Code"}),
                        },
                    ),
                ),
                (
                    "topics",
                    wagtail.fields.StreamField(
                        [("topic_panel", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Title of the documentation panel", "required": True},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Unique identifier in the url e.g. workflow",
                                    "max_length": 50,
                                    "required": True,
                                },
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Description of the documentation panel", "required": True},
                            ),
                            3: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Optional image for the documentation panel", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"default": False, "help_text": "Featured image", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("slug", 1), ("description", 2), ("image", 3), ("featured_image", 4)]],
                                {},
                            ),
                        },
                        help_text="Add topic cards to nest additional pages.",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Main hero or banner image for the top of the page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtailcache.cache.WagtailCacheMixin, "wagtailcore.page", models.Model),
        ),
    ]
