# Generated by Django 5.0.6 on 2024-07-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_fakecataloguepage"),
        ("home", "0005_rename_announcementpage_newsarticlepage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="video_url",
            field=models.TextField(blank=True),
        ),
    ]
