# Generated by Django 5.0.9 on 2025-01-21 17:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_hubpage_hero_image_hubpage_intro_hubpage_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubpage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='hubpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='hubpage',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='hubpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
