# Generated by Django 5.0.6 on 2024-07-08 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_homepage_about_image_homepage_contact_image_and_more"),
        ("home", "0006_homepage_video_url"),
    ]

    operations = []
