# Generated by Django 6.0.3 on 2026-03-24 13:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_aboutindexpage_body_alter_casestudiespage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_block", 6), ("accordion", 13), ("blockquote", 14), ("raw_html", 15), ("code", 18)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this content block.",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    4: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("background_color", 2),
                                ("heading", 3),
                                ("paragraph", 4),
                                ("image", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("title", 9), ("content", 10)]], {}),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("width", 0), ("alignment", 1), ("header_color", 7), ("content_color", 8), ("items", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    15: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    17: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    18: ("wagtail.blocks.StructBlock", [[("language", 16), ("code", 17)]], {"label": "Code"}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="casestudiespage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_block", 6), ("accordion", 13), ("blockquote", 14), ("raw_html", 15), ("code", 18)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this content block.",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    4: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("background_color", 2),
                                ("heading", 3),
                                ("paragraph", 4),
                                ("image", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("title", 9), ("content", 10)]], {}),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("width", 0), ("alignment", 1), ("header_color", 7), ("content_color", 8), ("items", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    15: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    17: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    18: ("wagtail.blocks.StructBlock", [[("language", 16), ("code", 17)]], {"label": "Code"}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="catalogueindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_block", 6), ("accordion", 13), ("blockquote", 14), ("raw_html", 15), ("code", 18)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this content block.",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    4: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("background_color", 2),
                                ("heading", 3),
                                ("paragraph", 4),
                                ("image", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("title", 9), ("content", 10)]], {}),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("width", 0), ("alignment", 1), ("header_color", 7), ("content_color", 8), ("items", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    15: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    17: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    18: ("wagtail.blocks.StructBlock", [[("language", 16), ("code", 17)]], {"label": "Code"}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="dataindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_block", 6), ("accordion", 13), ("blockquote", 14), ("raw_html", 15), ("code", 18)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this content block.",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    4: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("background_color", 2),
                                ("heading", 3),
                                ("paragraph", 4),
                                ("image", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("title", 9), ("content", 10)]], {}),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("width", 0), ("alignment", 1), ("header_color", 7), ("content_color", 8), ("items", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    15: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    17: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    18: ("wagtail.blocks.StructBlock", [[("language", 16), ("code", 17)]], {"label": "Code"}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="docsindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_block", 6), ("accordion", 13), ("blockquote", 14), ("raw_html", 15), ("code", 18)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this content block.",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    4: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("background_color", 2),
                                ("heading", 3),
                                ("paragraph", 4),
                                ("image", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("title", 9), ("content", 10)]], {}),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("width", 0), ("alignment", 1), ("header_color", 7), ("content_color", 8), ("items", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    15: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    17: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    18: ("wagtail.blocks.StructBlock", [[("language", 16), ("code", 17)]], {"label": "Code"}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_block", 6), ("accordion", 13), ("blockquote", 14), ("raw_html", 15), ("code", 18)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this content block.",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    4: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("background_color", 2),
                                ("heading", 3),
                                ("paragraph", 4),
                                ("image", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("title", 9), ("content", 10)]], {}),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("width", 0), ("alignment", 1), ("header_color", 7), ("content_color", 8), ("items", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    15: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    17: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    18: ("wagtail.blocks.StructBlock", [[("language", 16), ("code", 17)]], {"label": "Code"}),
                },
            ),
        ),
    ]
