# Generated by Django 5.0.9 on 2025-01-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_documentationpage_topics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentationpage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="DocsIndexPage",
        ),
        migrations.DeleteModel(
            name="DocumentationPage",
        ),
    ]
