# Generated by Django 5.0.6 on 2024-07-09 08:01

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_supportareapage_supportfaqpage_supportindexpage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticlepage",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 7, 9, 8, 1, 52, 778564), verbose_name="Post date"
            ),
            preserve_default=False,
        ),
    ]
