# Generated by Django 5.0.6 on 2024-07-09 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_rename_date_newsarticlepage_post_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsarticlepage",
            name="post_date",
        ),
    ]
