# Generated by Django 6.0.3 on 2026-03-27 14:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_alter_aboutindexpage_body_alter_casestudiespage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("content_block", 12),
                    ("image", 14),
                    ("accordion", 21),
                    ("embed", 24),
                    ("blockquote", 25),
                    ("raw_html", 26),
                    ("code", 29),
                    ("columns", 35),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("centre", "Centre"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment within a column layout.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this content block.",
                            "required": False,
                        },
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    5: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    6: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link the image to an internal page.", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link the image to an external URL. Page link takes priority if both are set.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("100", "Full width (100%)"),
                                ("75", "Three-quarters (75%)"),
                                ("50", "Half (50%)"),
                                ("25", "Quarter (25%)"),
                            ],
                            "help_text": "Control the display width of the image.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("rounded", "Rounded corners"),
                                ("square", "Square corners"),
                                ("pill", "Pill / circular"),
                            ],
                            "help_text": "Visual style for the image.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment of the image within the block.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("background_color", 3),
                                ("heading", 4),
                                ("paragraph", 5),
                                ("image", 6),
                                ("image_link_page", 7),
                                ("image_link_url", 8),
                                ("image_width", 9),
                                ("image_style", 10),
                                ("image_alignment", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("image", 13),
                                ("image_link_page", 7),
                                ("image_link_url", 8),
                                ("image_width", 9),
                                ("image_style", 10),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    17: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    18: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    19: ("wagtail.blocks.StructBlock", [[("title", 17), ("content", 18)]], {}),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("header_color", 15),
                                ("content_color", 16),
                                ("items", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Paste a URL to embed (YouTube, Vimeo, Spotify, etc.)."},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional caption below the embed.", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("width", 0), ("alignment", 1), ("vertical_alignment", 2), ("url", 22), ("caption", 23)]],
                        {},
                    ),
                    25: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    26: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    28: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    29: ("wagtail.blocks.StructBlock", [[("language", 27), ("code", 28)]], {"label": "Code"}),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("1-1", "Two columns (50 / 50)"),
                                ("1-2", "Two columns (33 / 67)"),
                                ("2-1", "Two columns (67 / 33)"),
                                ("1-1-1", "Three columns (33 / 33 / 33)"),
                                ("1-1-1-1", "Four columns (25 / 25 / 25 / 25)"),
                                ("1-2-1", "Three columns (25 / 50 / 25)"),
                            ],
                            "help_text": "Choose a column layout for this row.",
                        },
                    ),
                    31: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch text content to fill the full column height.",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("content_block", 12),
                                ("image", 14),
                                ("accordion", 21),
                                ("embed", 24),
                                ("blockquote", 25),
                                ("raw_html", 26),
                                ("code", 29),
                            ]
                        ],
                        {},
                    ),
                    33: ("wagtail.blocks.StructBlock", [[("stretch", 31), ("content", 32)]], {}),
                    34: ("wagtail.blocks.ListBlock", (33,), {"max_num": 4, "min_num": 1}),
                    35: ("wagtail.blocks.StructBlock", [[("layout", 30), ("columns", 34)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="casestudiespage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("content_block", 12),
                    ("image", 14),
                    ("accordion", 21),
                    ("embed", 24),
                    ("blockquote", 25),
                    ("raw_html", 26),
                    ("code", 29),
                    ("columns", 35),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("centre", "Centre"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment within a column layout.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this content block.",
                            "required": False,
                        },
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    5: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    6: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link the image to an internal page.", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link the image to an external URL. Page link takes priority if both are set.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("100", "Full width (100%)"),
                                ("75", "Three-quarters (75%)"),
                                ("50", "Half (50%)"),
                                ("25", "Quarter (25%)"),
                            ],
                            "help_text": "Control the display width of the image.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("rounded", "Rounded corners"),
                                ("square", "Square corners"),
                                ("pill", "Pill / circular"),
                            ],
                            "help_text": "Visual style for the image.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment of the image within the block.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("background_color", 3),
                                ("heading", 4),
                                ("paragraph", 5),
                                ("image", 6),
                                ("image_link_page", 7),
                                ("image_link_url", 8),
                                ("image_width", 9),
                                ("image_style", 10),
                                ("image_alignment", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("image", 13),
                                ("image_link_page", 7),
                                ("image_link_url", 8),
                                ("image_width", 9),
                                ("image_style", 10),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    17: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    18: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    19: ("wagtail.blocks.StructBlock", [[("title", 17), ("content", 18)]], {}),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("header_color", 15),
                                ("content_color", 16),
                                ("items", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Paste a URL to embed (YouTube, Vimeo, Spotify, etc.)."},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional caption below the embed.", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("width", 0), ("alignment", 1), ("vertical_alignment", 2), ("url", 22), ("caption", 23)]],
                        {},
                    ),
                    25: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    26: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    28: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    29: ("wagtail.blocks.StructBlock", [[("language", 27), ("code", 28)]], {"label": "Code"}),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("1-1", "Two columns (50 / 50)"),
                                ("1-2", "Two columns (33 / 67)"),
                                ("2-1", "Two columns (67 / 33)"),
                                ("1-1-1", "Three columns (33 / 33 / 33)"),
                                ("1-1-1-1", "Four columns (25 / 25 / 25 / 25)"),
                                ("1-2-1", "Three columns (25 / 50 / 25)"),
                            ],
                            "help_text": "Choose a column layout for this row.",
                        },
                    ),
                    31: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch text content to fill the full column height.",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("content_block", 12),
                                ("image", 14),
                                ("accordion", 21),
                                ("embed", 24),
                                ("blockquote", 25),
                                ("raw_html", 26),
                                ("code", 29),
                            ]
                        ],
                        {},
                    ),
                    33: ("wagtail.blocks.StructBlock", [[("stretch", 31), ("content", 32)]], {}),
                    34: ("wagtail.blocks.ListBlock", (33,), {"max_num": 4, "min_num": 1}),
                    35: ("wagtail.blocks.StructBlock", [[("layout", 30), ("columns", 34)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="catalogueindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("content_block", 12),
                    ("image", 14),
                    ("accordion", 21),
                    ("embed", 24),
                    ("blockquote", 25),
                    ("raw_html", 26),
                    ("code", 29),
                    ("columns", 35),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("centre", "Centre"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment within a column layout.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this content block.",
                            "required": False,
                        },
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    5: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    6: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link the image to an internal page.", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link the image to an external URL. Page link takes priority if both are set.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("100", "Full width (100%)"),
                                ("75", "Three-quarters (75%)"),
                                ("50", "Half (50%)"),
                                ("25", "Quarter (25%)"),
                            ],
                            "help_text": "Control the display width of the image.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("rounded", "Rounded corners"),
                                ("square", "Square corners"),
                                ("pill", "Pill / circular"),
                            ],
                            "help_text": "Visual style for the image.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment of the image within the block.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("background_color", 3),
                                ("heading", 4),
                                ("paragraph", 5),
                                ("image", 6),
                                ("image_link_page", 7),
                                ("image_link_url", 8),
                                ("image_width", 9),
                                ("image_style", 10),
                                ("image_alignment", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("image", 13),
                                ("image_link_page", 7),
                                ("image_link_url", 8),
                                ("image_width", 9),
                                ("image_style", 10),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    17: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    18: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    19: ("wagtail.blocks.StructBlock", [[("title", 17), ("content", 18)]], {}),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("header_color", 15),
                                ("content_color", 16),
                                ("items", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Paste a URL to embed (YouTube, Vimeo, Spotify, etc.)."},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional caption below the embed.", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("width", 0), ("alignment", 1), ("vertical_alignment", 2), ("url", 22), ("caption", 23)]],
                        {},
                    ),
                    25: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    26: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    28: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    29: ("wagtail.blocks.StructBlock", [[("language", 27), ("code", 28)]], {"label": "Code"}),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("1-1", "Two columns (50 / 50)"),
                                ("1-2", "Two columns (33 / 67)"),
                                ("2-1", "Two columns (67 / 33)"),
                                ("1-1-1", "Three columns (33 / 33 / 33)"),
                                ("1-1-1-1", "Four columns (25 / 25 / 25 / 25)"),
                                ("1-2-1", "Three columns (25 / 50 / 25)"),
                            ],
                            "help_text": "Choose a column layout for this row.",
                        },
                    ),
                    31: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch text content to fill the full column height.",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("content_block", 12),
                                ("image", 14),
                                ("accordion", 21),
                                ("embed", 24),
                                ("blockquote", 25),
                                ("raw_html", 26),
                                ("code", 29),
                            ]
                        ],
                        {},
                    ),
                    33: ("wagtail.blocks.StructBlock", [[("stretch", 31), ("content", 32)]], {}),
                    34: ("wagtail.blocks.ListBlock", (33,), {"max_num": 4, "min_num": 1}),
                    35: ("wagtail.blocks.StructBlock", [[("layout", 30), ("columns", 34)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="dataindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("content_block", 12),
                    ("image", 14),
                    ("accordion", 21),
                    ("embed", 24),
                    ("blockquote", 25),
                    ("raw_html", 26),
                    ("code", 29),
                    ("columns", 35),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("centre", "Centre"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment within a column layout.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this content block.",
                            "required": False,
                        },
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    5: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    6: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link the image to an internal page.", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link the image to an external URL. Page link takes priority if both are set.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("100", "Full width (100%)"),
                                ("75", "Three-quarters (75%)"),
                                ("50", "Half (50%)"),
                                ("25", "Quarter (25%)"),
                            ],
                            "help_text": "Control the display width of the image.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("rounded", "Rounded corners"),
                                ("square", "Square corners"),
                                ("pill", "Pill / circular"),
                            ],
                            "help_text": "Visual style for the image.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment of the image within the block.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("background_color", 3),
                                ("heading", 4),
                                ("paragraph", 5),
                                ("image", 6),
                                ("image_link_page", 7),
                                ("image_link_url", 8),
                                ("image_width", 9),
                                ("image_style", 10),
                                ("image_alignment", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("image", 13),
                                ("image_link_page", 7),
                                ("image_link_url", 8),
                                ("image_width", 9),
                                ("image_style", 10),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    17: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    18: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    19: ("wagtail.blocks.StructBlock", [[("title", 17), ("content", 18)]], {}),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("header_color", 15),
                                ("content_color", 16),
                                ("items", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Paste a URL to embed (YouTube, Vimeo, Spotify, etc.)."},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional caption below the embed.", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("width", 0), ("alignment", 1), ("vertical_alignment", 2), ("url", 22), ("caption", 23)]],
                        {},
                    ),
                    25: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    26: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    28: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    29: ("wagtail.blocks.StructBlock", [[("language", 27), ("code", 28)]], {"label": "Code"}),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("1-1", "Two columns (50 / 50)"),
                                ("1-2", "Two columns (33 / 67)"),
                                ("2-1", "Two columns (67 / 33)"),
                                ("1-1-1", "Three columns (33 / 33 / 33)"),
                                ("1-1-1-1", "Four columns (25 / 25 / 25 / 25)"),
                                ("1-2-1", "Three columns (25 / 50 / 25)"),
                            ],
                            "help_text": "Choose a column layout for this row.",
                        },
                    ),
                    31: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch text content to fill the full column height.",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("content_block", 12),
                                ("image", 14),
                                ("accordion", 21),
                                ("embed", 24),
                                ("blockquote", 25),
                                ("raw_html", 26),
                                ("code", 29),
                            ]
                        ],
                        {},
                    ),
                    33: ("wagtail.blocks.StructBlock", [[("stretch", 31), ("content", 32)]], {}),
                    34: ("wagtail.blocks.ListBlock", (33,), {"max_num": 4, "min_num": 1}),
                    35: ("wagtail.blocks.StructBlock", [[("layout", 30), ("columns", 34)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="docsindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("content_block", 12),
                    ("image", 14),
                    ("accordion", 21),
                    ("embed", 24),
                    ("blockquote", 25),
                    ("raw_html", 26),
                    ("code", 29),
                    ("columns", 35),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("centre", "Centre"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment within a column layout.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this content block.",
                            "required": False,
                        },
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    5: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    6: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link the image to an internal page.", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link the image to an external URL. Page link takes priority if both are set.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("100", "Full width (100%)"),
                                ("75", "Three-quarters (75%)"),
                                ("50", "Half (50%)"),
                                ("25", "Quarter (25%)"),
                            ],
                            "help_text": "Control the display width of the image.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("rounded", "Rounded corners"),
                                ("square", "Square corners"),
                                ("pill", "Pill / circular"),
                            ],
                            "help_text": "Visual style for the image.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment of the image within the block.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("background_color", 3),
                                ("heading", 4),
                                ("paragraph", 5),
                                ("image", 6),
                                ("image_link_page", 7),
                                ("image_link_url", 8),
                                ("image_width", 9),
                                ("image_style", 10),
                                ("image_alignment", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("image", 13),
                                ("image_link_page", 7),
                                ("image_link_url", 8),
                                ("image_width", 9),
                                ("image_style", 10),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    17: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    18: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    19: ("wagtail.blocks.StructBlock", [[("title", 17), ("content", 18)]], {}),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("header_color", 15),
                                ("content_color", 16),
                                ("items", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Paste a URL to embed (YouTube, Vimeo, Spotify, etc.)."},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional caption below the embed.", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("width", 0), ("alignment", 1), ("vertical_alignment", 2), ("url", 22), ("caption", 23)]],
                        {},
                    ),
                    25: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    26: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    28: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    29: ("wagtail.blocks.StructBlock", [[("language", 27), ("code", 28)]], {"label": "Code"}),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("1-1", "Two columns (50 / 50)"),
                                ("1-2", "Two columns (33 / 67)"),
                                ("2-1", "Two columns (67 / 33)"),
                                ("1-1-1", "Three columns (33 / 33 / 33)"),
                                ("1-1-1-1", "Four columns (25 / 25 / 25 / 25)"),
                                ("1-2-1", "Three columns (25 / 50 / 25)"),
                            ],
                            "help_text": "Choose a column layout for this row.",
                        },
                    ),
                    31: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch text content to fill the full column height.",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("content_block", 12),
                                ("image", 14),
                                ("accordion", 21),
                                ("embed", 24),
                                ("blockquote", 25),
                                ("raw_html", 26),
                                ("code", 29),
                            ]
                        ],
                        {},
                    ),
                    33: ("wagtail.blocks.StructBlock", [[("stretch", 31), ("content", 32)]], {}),
                    34: ("wagtail.blocks.ListBlock", (33,), {"max_num": 4, "min_num": 1}),
                    35: ("wagtail.blocks.StructBlock", [[("layout", 30), ("columns", 34)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("content_block", 12),
                    ("image", 14),
                    ("accordion", 21),
                    ("embed", 24),
                    ("blockquote", 25),
                    ("raw_html", 26),
                    ("code", 29),
                    ("columns", 35),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("centre", "Centre"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment within a column layout.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this content block.",
                            "required": False,
                        },
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    5: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    6: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link the image to an internal page.", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link the image to an external URL. Page link takes priority if both are set.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("100", "Full width (100%)"),
                                ("75", "Three-quarters (75%)"),
                                ("50", "Half (50%)"),
                                ("25", "Quarter (25%)"),
                            ],
                            "help_text": "Control the display width of the image.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("rounded", "Rounded corners"),
                                ("square", "Square corners"),
                                ("pill", "Pill / circular"),
                            ],
                            "help_text": "Visual style for the image.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment of the image within the block.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("background_color", 3),
                                ("heading", 4),
                                ("paragraph", 5),
                                ("image", 6),
                                ("image_link_page", 7),
                                ("image_link_url", 8),
                                ("image_width", 9),
                                ("image_style", 10),
                                ("image_alignment", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("image", 13),
                                ("image_link_page", 7),
                                ("image_link_url", 8),
                                ("image_width", 9),
                                ("image_style", 10),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    17: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    18: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    19: ("wagtail.blocks.StructBlock", [[("title", 17), ("content", 18)]], {}),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("alignment", 1),
                                ("vertical_alignment", 2),
                                ("header_color", 15),
                                ("content_color", 16),
                                ("items", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Paste a URL to embed (YouTube, Vimeo, Spotify, etc.)."},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional caption below the embed.", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("width", 0), ("alignment", 1), ("vertical_alignment", 2), ("url", 22), ("caption", 23)]],
                        {},
                    ),
                    25: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    26: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    28: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    29: ("wagtail.blocks.StructBlock", [[("language", 27), ("code", 28)]], {"label": "Code"}),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("1-1", "Two columns (50 / 50)"),
                                ("1-2", "Two columns (33 / 67)"),
                                ("2-1", "Two columns (67 / 33)"),
                                ("1-1-1", "Three columns (33 / 33 / 33)"),
                                ("1-1-1-1", "Four columns (25 / 25 / 25 / 25)"),
                                ("1-2-1", "Three columns (25 / 50 / 25)"),
                            ],
                            "help_text": "Choose a column layout for this row.",
                        },
                    ),
                    31: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch text content to fill the full column height.",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("content_block", 12),
                                ("image", 14),
                                ("accordion", 21),
                                ("embed", 24),
                                ("blockquote", 25),
                                ("raw_html", 26),
                                ("code", 29),
                            ]
                        ],
                        {},
                    ),
                    33: ("wagtail.blocks.StructBlock", [[("stretch", 31), ("content", 32)]], {}),
                    34: ("wagtail.blocks.ListBlock", (33,), {"max_num": 4, "min_num": 1}),
                    35: ("wagtail.blocks.StructBlock", [[("layout", 30), ("columns", 34)]], {}),
                },
            ),
        ),
    ]
