# Generated by Django 6.0.3 on 2026-03-27 15:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_alter_aboutindexpage_body_alter_casestudiespage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutindexpage",
            name="intro_background_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                default="default",
                help_text="Background color for the intro section.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aboutindexpage",
            name="intro_full_width_background",
            field=models.BooleanField(
                default=False, help_text="Stretch the intro background to the full width of the page."
            ),
        ),
        migrations.AddField(
            model_name="aboutindexpage",
            name="topics_background_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                default="default",
                help_text="Background color for the topics grid section.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aboutindexpage",
            name="topics_full_width_background",
            field=models.BooleanField(
                default=False, help_text="Stretch the topics background to the full width of the page."
            ),
        ),
        migrations.AddField(
            model_name="casestudiespage",
            name="intro_background_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                default="default",
                help_text="Background color for the intro section.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="casestudiespage",
            name="intro_full_width_background",
            field=models.BooleanField(
                default=False, help_text="Stretch the intro background to the full width of the page."
            ),
        ),
        migrations.AddField(
            model_name="casestudiespage",
            name="topics_background_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                default="default",
                help_text="Background color for the topics grid section.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="casestudiespage",
            name="topics_full_width_background",
            field=models.BooleanField(
                default=False, help_text="Stretch the topics background to the full width of the page."
            ),
        ),
        migrations.AddField(
            model_name="catalogueindexpage",
            name="intro_background_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                default="default",
                help_text="Background color for the intro section.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="catalogueindexpage",
            name="intro_full_width_background",
            field=models.BooleanField(
                default=False, help_text="Stretch the intro background to the full width of the page."
            ),
        ),
        migrations.AddField(
            model_name="catalogueindexpage",
            name="topics_background_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                default="default",
                help_text="Background color for the topics grid section.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="catalogueindexpage",
            name="topics_full_width_background",
            field=models.BooleanField(
                default=False, help_text="Stretch the topics background to the full width of the page."
            ),
        ),
        migrations.AddField(
            model_name="dataindexpage",
            name="intro_background_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                default="default",
                help_text="Background color for the intro section.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dataindexpage",
            name="intro_full_width_background",
            field=models.BooleanField(
                default=False, help_text="Stretch the intro background to the full width of the page."
            ),
        ),
        migrations.AddField(
            model_name="dataindexpage",
            name="topics_background_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                default="default",
                help_text="Background color for the topics grid section.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dataindexpage",
            name="topics_full_width_background",
            field=models.BooleanField(
                default=False, help_text="Stretch the topics background to the full width of the page."
            ),
        ),
        migrations.AddField(
            model_name="docsindexpage",
            name="intro_background_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                default="default",
                help_text="Background color for the intro section.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="docsindexpage",
            name="intro_full_width_background",
            field=models.BooleanField(
                default=False, help_text="Stretch the intro background to the full width of the page."
            ),
        ),
        migrations.AddField(
            model_name="docsindexpage",
            name="topics_background_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                default="default",
                help_text="Background color for the topics grid section.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="docsindexpage",
            name="topics_full_width_background",
            field=models.BooleanField(
                default=False, help_text="Stretch the topics background to the full width of the page."
            ),
        ),
        migrations.AddField(
            model_name="documentationpage",
            name="intro_background_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                default="default",
                help_text="Background color for the intro section.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="documentationpage",
            name="intro_full_width_background",
            field=models.BooleanField(
                default=False, help_text="Stretch the intro background to the full width of the page."
            ),
        ),
        migrations.AddField(
            model_name="documentationpage",
            name="topics_background_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                default="default",
                help_text="Background color for the topics grid section.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="documentationpage",
            name="topics_full_width_background",
            field=models.BooleanField(
                default=False, help_text="Stretch the topics background to the full width of the page."
            ),
        ),
        migrations.AddField(
            model_name="genericpage",
            name="intro_background_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                default="default",
                help_text="Background color for the intro section.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="genericpage",
            name="intro_full_width_background",
            field=models.BooleanField(
                default=False, help_text="Stretch the intro background to the full width of the page."
            ),
        ),
        migrations.AddField(
            model_name="genericpage",
            name="topics_background_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                default="default",
                help_text="Background color for the topics grid section.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="genericpage",
            name="topics_full_width_background",
            field=models.BooleanField(
                default=False, help_text="Stretch the topics background to the full width of the page."
            ),
        ),
        migrations.AlterField(
            model_name="aboutindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("content_block", 13),
                    ("image", 15),
                    ("accordion", 22),
                    ("embed", 25),
                    ("blockquote", 26),
                    ("raw_html", 27),
                    ("code", 30),
                    ("columns", 36),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this block.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch the background to the full width of the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("centre", "Centre"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment within a column layout.",
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link the image to an internal page.", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link the image to an external URL. Page link takes priority if both are set.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("100", "Full width (100%)"),
                                ("75", "Three-quarters (75%)"),
                                ("50", "Half (50%)"),
                                ("25", "Quarter (25%)"),
                            ],
                            "help_text": "Control the display width of the image.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("rounded", "Rounded corners"),
                                ("square", "Square corners"),
                                ("pill", "Pill / circular"),
                            ],
                            "help_text": "Visual style for the image.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment of the image within the block.",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("heading", 5),
                                ("paragraph", 6),
                                ("image", 7),
                                ("image_link_page", 8),
                                ("image_link_url", 9),
                                ("image_width", 10),
                                ("image_style", 11),
                                ("image_alignment", 12),
                            ]
                        ],
                        {},
                    ),
                    14: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("image", 14),
                                ("image_link_page", 8),
                                ("image_link_url", 9),
                                ("image_width", 10),
                                ("image_style", 11),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    18: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    19: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    20: ("wagtail.blocks.StructBlock", [[("title", 18), ("content", 19)]], {}),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("header_color", 16),
                                ("content_color", 17),
                                ("items", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Paste a URL to embed (YouTube, Vimeo, Spotify, etc.)."},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional caption below the embed.", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("url", 23),
                                ("caption", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    27: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    29: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    30: ("wagtail.blocks.StructBlock", [[("language", 28), ("code", 29)]], {"label": "Code"}),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("1-1", "Two columns (50 / 50)"),
                                ("1-2", "Two columns (33 / 67)"),
                                ("2-1", "Two columns (67 / 33)"),
                                ("1-1-1", "Three columns (33 / 33 / 33)"),
                                ("1-1-1-1", "Four columns (25 / 25 / 25 / 25)"),
                                ("1-2-1", "Three columns (25 / 50 / 25)"),
                            ],
                            "help_text": "Choose a column layout for this row.",
                        },
                    ),
                    32: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch text content to fill the full column height.",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("content_block", 13),
                                ("image", 15),
                                ("accordion", 22),
                                ("embed", 25),
                                ("blockquote", 26),
                                ("raw_html", 27),
                                ("code", 30),
                            ]
                        ],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("background_color", 0), ("full_width_background", 1), ("stretch", 32), ("content", 33)]],
                        {},
                    ),
                    35: ("wagtail.blocks.ListBlock", (34,), {"max_num": 4, "min_num": 1}),
                    36: ("wagtail.blocks.StructBlock", [[("layout", 31), ("columns", 35)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="casestudiespage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("content_block", 13),
                    ("image", 15),
                    ("accordion", 22),
                    ("embed", 25),
                    ("blockquote", 26),
                    ("raw_html", 27),
                    ("code", 30),
                    ("columns", 36),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this block.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch the background to the full width of the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("centre", "Centre"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment within a column layout.",
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link the image to an internal page.", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link the image to an external URL. Page link takes priority if both are set.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("100", "Full width (100%)"),
                                ("75", "Three-quarters (75%)"),
                                ("50", "Half (50%)"),
                                ("25", "Quarter (25%)"),
                            ],
                            "help_text": "Control the display width of the image.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("rounded", "Rounded corners"),
                                ("square", "Square corners"),
                                ("pill", "Pill / circular"),
                            ],
                            "help_text": "Visual style for the image.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment of the image within the block.",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("heading", 5),
                                ("paragraph", 6),
                                ("image", 7),
                                ("image_link_page", 8),
                                ("image_link_url", 9),
                                ("image_width", 10),
                                ("image_style", 11),
                                ("image_alignment", 12),
                            ]
                        ],
                        {},
                    ),
                    14: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("image", 14),
                                ("image_link_page", 8),
                                ("image_link_url", 9),
                                ("image_width", 10),
                                ("image_style", 11),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    18: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    19: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    20: ("wagtail.blocks.StructBlock", [[("title", 18), ("content", 19)]], {}),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("header_color", 16),
                                ("content_color", 17),
                                ("items", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Paste a URL to embed (YouTube, Vimeo, Spotify, etc.)."},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional caption below the embed.", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("url", 23),
                                ("caption", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    27: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    29: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    30: ("wagtail.blocks.StructBlock", [[("language", 28), ("code", 29)]], {"label": "Code"}),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("1-1", "Two columns (50 / 50)"),
                                ("1-2", "Two columns (33 / 67)"),
                                ("2-1", "Two columns (67 / 33)"),
                                ("1-1-1", "Three columns (33 / 33 / 33)"),
                                ("1-1-1-1", "Four columns (25 / 25 / 25 / 25)"),
                                ("1-2-1", "Three columns (25 / 50 / 25)"),
                            ],
                            "help_text": "Choose a column layout for this row.",
                        },
                    ),
                    32: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch text content to fill the full column height.",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("content_block", 13),
                                ("image", 15),
                                ("accordion", 22),
                                ("embed", 25),
                                ("blockquote", 26),
                                ("raw_html", 27),
                                ("code", 30),
                            ]
                        ],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("background_color", 0), ("full_width_background", 1), ("stretch", 32), ("content", 33)]],
                        {},
                    ),
                    35: ("wagtail.blocks.ListBlock", (34,), {"max_num": 4, "min_num": 1}),
                    36: ("wagtail.blocks.StructBlock", [[("layout", 31), ("columns", 35)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="catalogueindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("content_block", 13),
                    ("image", 15),
                    ("accordion", 22),
                    ("embed", 25),
                    ("blockquote", 26),
                    ("raw_html", 27),
                    ("code", 30),
                    ("columns", 36),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this block.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch the background to the full width of the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("centre", "Centre"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment within a column layout.",
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link the image to an internal page.", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link the image to an external URL. Page link takes priority if both are set.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("100", "Full width (100%)"),
                                ("75", "Three-quarters (75%)"),
                                ("50", "Half (50%)"),
                                ("25", "Quarter (25%)"),
                            ],
                            "help_text": "Control the display width of the image.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("rounded", "Rounded corners"),
                                ("square", "Square corners"),
                                ("pill", "Pill / circular"),
                            ],
                            "help_text": "Visual style for the image.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment of the image within the block.",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("heading", 5),
                                ("paragraph", 6),
                                ("image", 7),
                                ("image_link_page", 8),
                                ("image_link_url", 9),
                                ("image_width", 10),
                                ("image_style", 11),
                                ("image_alignment", 12),
                            ]
                        ],
                        {},
                    ),
                    14: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("image", 14),
                                ("image_link_page", 8),
                                ("image_link_url", 9),
                                ("image_width", 10),
                                ("image_style", 11),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    18: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    19: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    20: ("wagtail.blocks.StructBlock", [[("title", 18), ("content", 19)]], {}),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("header_color", 16),
                                ("content_color", 17),
                                ("items", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Paste a URL to embed (YouTube, Vimeo, Spotify, etc.)."},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional caption below the embed.", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("url", 23),
                                ("caption", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    27: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    29: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    30: ("wagtail.blocks.StructBlock", [[("language", 28), ("code", 29)]], {"label": "Code"}),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("1-1", "Two columns (50 / 50)"),
                                ("1-2", "Two columns (33 / 67)"),
                                ("2-1", "Two columns (67 / 33)"),
                                ("1-1-1", "Three columns (33 / 33 / 33)"),
                                ("1-1-1-1", "Four columns (25 / 25 / 25 / 25)"),
                                ("1-2-1", "Three columns (25 / 50 / 25)"),
                            ],
                            "help_text": "Choose a column layout for this row.",
                        },
                    ),
                    32: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch text content to fill the full column height.",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("content_block", 13),
                                ("image", 15),
                                ("accordion", 22),
                                ("embed", 25),
                                ("blockquote", 26),
                                ("raw_html", 27),
                                ("code", 30),
                            ]
                        ],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("background_color", 0), ("full_width_background", 1), ("stretch", 32), ("content", 33)]],
                        {},
                    ),
                    35: ("wagtail.blocks.ListBlock", (34,), {"max_num": 4, "min_num": 1}),
                    36: ("wagtail.blocks.StructBlock", [[("layout", 31), ("columns", 35)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="dataindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("content_block", 13),
                    ("image", 15),
                    ("accordion", 22),
                    ("embed", 25),
                    ("blockquote", 26),
                    ("raw_html", 27),
                    ("code", 30),
                    ("columns", 36),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this block.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch the background to the full width of the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("centre", "Centre"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment within a column layout.",
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link the image to an internal page.", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link the image to an external URL. Page link takes priority if both are set.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("100", "Full width (100%)"),
                                ("75", "Three-quarters (75%)"),
                                ("50", "Half (50%)"),
                                ("25", "Quarter (25%)"),
                            ],
                            "help_text": "Control the display width of the image.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("rounded", "Rounded corners"),
                                ("square", "Square corners"),
                                ("pill", "Pill / circular"),
                            ],
                            "help_text": "Visual style for the image.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment of the image within the block.",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("heading", 5),
                                ("paragraph", 6),
                                ("image", 7),
                                ("image_link_page", 8),
                                ("image_link_url", 9),
                                ("image_width", 10),
                                ("image_style", 11),
                                ("image_alignment", 12),
                            ]
                        ],
                        {},
                    ),
                    14: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("image", 14),
                                ("image_link_page", 8),
                                ("image_link_url", 9),
                                ("image_width", 10),
                                ("image_style", 11),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    18: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    19: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    20: ("wagtail.blocks.StructBlock", [[("title", 18), ("content", 19)]], {}),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("header_color", 16),
                                ("content_color", 17),
                                ("items", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Paste a URL to embed (YouTube, Vimeo, Spotify, etc.)."},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional caption below the embed.", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("url", 23),
                                ("caption", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    27: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    29: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    30: ("wagtail.blocks.StructBlock", [[("language", 28), ("code", 29)]], {"label": "Code"}),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("1-1", "Two columns (50 / 50)"),
                                ("1-2", "Two columns (33 / 67)"),
                                ("2-1", "Two columns (67 / 33)"),
                                ("1-1-1", "Three columns (33 / 33 / 33)"),
                                ("1-1-1-1", "Four columns (25 / 25 / 25 / 25)"),
                                ("1-2-1", "Three columns (25 / 50 / 25)"),
                            ],
                            "help_text": "Choose a column layout for this row.",
                        },
                    ),
                    32: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch text content to fill the full column height.",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("content_block", 13),
                                ("image", 15),
                                ("accordion", 22),
                                ("embed", 25),
                                ("blockquote", 26),
                                ("raw_html", 27),
                                ("code", 30),
                            ]
                        ],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("background_color", 0), ("full_width_background", 1), ("stretch", 32), ("content", 33)]],
                        {},
                    ),
                    35: ("wagtail.blocks.ListBlock", (34,), {"max_num": 4, "min_num": 1}),
                    36: ("wagtail.blocks.StructBlock", [[("layout", 31), ("columns", 35)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="docsindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("content_block", 13),
                    ("image", 15),
                    ("accordion", 22),
                    ("embed", 25),
                    ("blockquote", 26),
                    ("raw_html", 27),
                    ("code", 30),
                    ("columns", 36),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this block.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch the background to the full width of the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("centre", "Centre"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment within a column layout.",
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link the image to an internal page.", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link the image to an external URL. Page link takes priority if both are set.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("100", "Full width (100%)"),
                                ("75", "Three-quarters (75%)"),
                                ("50", "Half (50%)"),
                                ("25", "Quarter (25%)"),
                            ],
                            "help_text": "Control the display width of the image.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("rounded", "Rounded corners"),
                                ("square", "Square corners"),
                                ("pill", "Pill / circular"),
                            ],
                            "help_text": "Visual style for the image.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment of the image within the block.",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("heading", 5),
                                ("paragraph", 6),
                                ("image", 7),
                                ("image_link_page", 8),
                                ("image_link_url", 9),
                                ("image_width", 10),
                                ("image_style", 11),
                                ("image_alignment", 12),
                            ]
                        ],
                        {},
                    ),
                    14: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("image", 14),
                                ("image_link_page", 8),
                                ("image_link_url", 9),
                                ("image_width", 10),
                                ("image_style", 11),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    18: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    19: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    20: ("wagtail.blocks.StructBlock", [[("title", 18), ("content", 19)]], {}),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("header_color", 16),
                                ("content_color", 17),
                                ("items", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Paste a URL to embed (YouTube, Vimeo, Spotify, etc.)."},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional caption below the embed.", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("url", 23),
                                ("caption", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    27: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    29: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    30: ("wagtail.blocks.StructBlock", [[("language", 28), ("code", 29)]], {"label": "Code"}),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("1-1", "Two columns (50 / 50)"),
                                ("1-2", "Two columns (33 / 67)"),
                                ("2-1", "Two columns (67 / 33)"),
                                ("1-1-1", "Three columns (33 / 33 / 33)"),
                                ("1-1-1-1", "Four columns (25 / 25 / 25 / 25)"),
                                ("1-2-1", "Three columns (25 / 50 / 25)"),
                            ],
                            "help_text": "Choose a column layout for this row.",
                        },
                    ),
                    32: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch text content to fill the full column height.",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("content_block", 13),
                                ("image", 15),
                                ("accordion", 22),
                                ("embed", 25),
                                ("blockquote", 26),
                                ("raw_html", 27),
                                ("code", 30),
                            ]
                        ],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("background_color", 0), ("full_width_background", 1), ("stretch", 32), ("content", 33)]],
                        {},
                    ),
                    35: ("wagtail.blocks.ListBlock", (34,), {"max_num": 4, "min_num": 1}),
                    36: ("wagtail.blocks.StructBlock", [[("layout", 31), ("columns", 35)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("content_block", 13),
                    ("image", 15),
                    ("accordion", 22),
                    ("embed", 25),
                    ("blockquote", 26),
                    ("raw_html", 27),
                    ("code", 30),
                    ("columns", 36),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for this block.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch the background to the full width of the page.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                            "help_text": "Control how wide this block spans.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment within the page.",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("centre", "Centre"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment within a column layout.",
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link the image to an internal page.", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link the image to an external URL. Page link takes priority if both are set.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("100", "Full width (100%)"),
                                ("75", "Three-quarters (75%)"),
                                ("50", "Half (50%)"),
                                ("25", "Quarter (25%)"),
                            ],
                            "help_text": "Control the display width of the image.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("rounded", "Rounded corners"),
                                ("square", "Square corners"),
                                ("pill", "Pill / circular"),
                            ],
                            "help_text": "Visual style for the image.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                            "help_text": "Horizontal alignment of the image within the block.",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("heading", 5),
                                ("paragraph", 6),
                                ("image", 7),
                                ("image_link_page", 8),
                                ("image_link_url", 9),
                                ("image_width", 10),
                                ("image_style", 11),
                                ("image_alignment", 12),
                            ]
                        ],
                        {},
                    ),
                    14: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("image", 14),
                                ("image_link_page", 8),
                                ("image_link_url", 9),
                                ("image_width", 10),
                                ("image_style", 11),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion headers.",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default (theme)"),
                                ("nceo-purple", "NCEO Purple"),
                                ("navy", "Navy"),
                                ("light-grey", "Light Grey"),
                                ("steel", "Steel"),
                                ("blue", "Blue"),
                            ],
                            "help_text": "Background color for accordion content panels.",
                            "required": False,
                        },
                    ),
                    18: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
                    19: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content revealed when expanded", "required": True},
                    ),
                    20: ("wagtail.blocks.StructBlock", [[("title", 18), ("content", 19)]], {}),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("header_color", 16),
                                ("content_color", 17),
                                ("items", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Paste a URL to embed (YouTube, Vimeo, Spotify, etc.)."},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional caption below the embed.", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("full_width_background", 1),
                                ("width", 2),
                                ("alignment", 3),
                                ("vertical_alignment", 4),
                                ("url", 23),
                                ("caption", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    27: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    29: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
                    30: ("wagtail.blocks.StructBlock", [[("language", 28), ("code", 29)]], {"label": "Code"}),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("1-1", "Two columns (50 / 50)"),
                                ("1-2", "Two columns (33 / 67)"),
                                ("2-1", "Two columns (67 / 33)"),
                                ("1-1-1", "Three columns (33 / 33 / 33)"),
                                ("1-1-1-1", "Four columns (25 / 25 / 25 / 25)"),
                                ("1-2-1", "Three columns (25 / 50 / 25)"),
                            ],
                            "help_text": "Choose a column layout for this row.",
                        },
                    ),
                    32: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch text content to fill the full column height.",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("content_block", 13),
                                ("image", 15),
                                ("accordion", 22),
                                ("embed", 25),
                                ("blockquote", 26),
                                ("raw_html", 27),
                                ("code", 30),
                            ]
                        ],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("background_color", 0), ("full_width_background", 1), ("stretch", 32), ("content", 33)]],
                        {},
                    ),
                    35: ("wagtail.blocks.ListBlock", (34,), {"max_num": 4, "min_num": 1}),
                    36: ("wagtail.blocks.StructBlock", [[("layout", 31), ("columns", 35)]], {}),
                },
            ),
        ),
    ]
