# Generated by Django 6.0.4 on 2026-04-17 09:07
#
# Merge the old per-page `topics` StreamField into `body` as a new
# `topics_grid` block so editors can reorder sections freely.
#
# One-way migration: reverse cannot faithfully reconstruct the old
# single-section layout once editors move or duplicate topics_grid
# blocks. Snapshot the DB before applying in prod.

import json
import uuid

import wagtail.fields
from django.db import migrations
from django.db.models import F, JSONField
from django.db.models.functions import Cast
from wagtail.blocks import StreamValue

_PAGE_MODELS = [
    "aboutindexpage",
    "casestudiespage",
    "catalogueindexpage",
    "dataindexpage",
    "docsindexpage",
    "genericpage",
]


def _wrap_topics_as_grid(topics_raw, bg_color, full_width):
    if not topics_raw:
        return None
    return {
        "type": "topics_grid",
        "value": {
            "background_color": bg_color or "default",
            "full_width_background": bool(full_width),
            "topics": [
                {
                    "type": "item",
                    "value": item["value"],
                    "id": str(uuid.uuid4()),
                }
                for item in topics_raw
            ],
        },
        "id": str(uuid.uuid4()),
    }


def migrate_topics_into_body(apps, schema_editor):
    Revision = apps.get_model("wagtailcore", "Revision")
    ContentType = apps.get_model("contenttypes", "ContentType")

    for model_name in _PAGE_MODELS:
        Model = apps.get_model("home", model_name)
        ct = ContentType.objects.get_for_model(Model)
        body_stream_block = Model._meta.get_field("body").stream_block

        # Live/draft rows: read raw JSON via cast to bypass StreamField
        # deserialization edge cases in historical models.
        queryset = Model.objects.annotate(
            raw_body=Cast(F("body"), JSONField()),
            raw_topics=Cast(F("topics"), JSONField()),
        )

        updates = []
        for page in queryset.iterator(chunk_size=512):
            topics_raw = page.raw_topics or []
            grid = _wrap_topics_as_grid(
                topics_raw,
                page.topics_background_color,
                page.topics_full_width_background,
            )
            if grid is None:
                continue
            body_raw = list(page.raw_body or [])
            body_raw.insert(0, grid)
            page.body = StreamValue(body_stream_block, body_raw, is_lazy=True)
            updates.append(page)
            if len(updates) >= 512:
                Model.objects.bulk_update(updates, ["body"])
                updates = []
        if updates:
            Model.objects.bulk_update(updates, ["body"])

        # Revisions: content is a JSONField, but each field value inside
        # it is stored as a JSON-encoded string (see Wagtail's
        # MigrateStreamData.migrate_stream_data_forward).
        #
        # Default to an empty body stream when `body` is missing from a
        # revision's content rather than skipping: historical revisions
        # predating the `body` field still need their topics moved, or a
        # revert would silently drop them.
        for revision in Revision.objects.filter(content_type_id=ct.id).iterator(chunk_size=512):
            content = revision.content
            body_json = content.get("body") or "[]"
            topics_json = content.get("topics") or "[]"
            body_raw = json.loads(body_json) if body_json else []
            topics_raw = json.loads(topics_json) if topics_json else []
            grid = _wrap_topics_as_grid(
                topics_raw,
                content.get("topics_background_color"),
                content.get("topics_full_width_background"),
            )
            if grid is None:
                continue
            body_raw.insert(0, grid)
            content["body"] = json.dumps(body_raw)
            # Zero the old fields so a revision restore doesn't resurrect them.
            content["topics"] = json.dumps([])
            content.pop("topics_background_color", None)
            content.pop("topics_full_width_background", None)
            revision.content = content
            revision.save(update_fields=["content"])


# Reusable StreamField definition for the new body shape (with topics_grid).
_BODY_FIELD = wagtail.fields.StreamField(
    [
        ("content_block", 13),
        ("image", 15),
        ("accordion", 22),
        ("embed", 25),
        ("blockquote", 31),
        ("raw_html", 32),
        ("code", 35),
        ("columns", 41),
        ("topics_grid", 49),
    ],
    blank=True,
    block_lookup={
        0: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
        1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
        2: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
        3: (
            "wagtail.blocks.PageChooserBlock",
            (),
            {"help_text": "Link the image to an internal page.", "required": False},
        ),
        4: (
            "wagtail.blocks.URLBlock",
            (),
            {
                "help_text": "Link the image to an external URL. Page link takes priority if both are set.",
                "required": False,
            },
        ),
        5: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [
                    ("100", "Original dimensions (100%)"),
                    ("75", "75% of original dimensions"),
                    ("50", "50% of original dimensions"),
                    ("25", "25% of original dimensions"),
                ],
                "help_text": "Display width as a percentage of the image's original dimensions.",
                "required": False,
            },
        ),
        6: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("rounded", "Rounded corners"), ("square", "Square corners"), ("pill", "Pill / circular")],
                "help_text": "Visual style for the image.",
                "required": False,
            },
        ),
        7: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                "help_text": "Horizontal alignment of the image within the block.",
                "required": False,
            },
        ),
        8: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                "help_text": "Control how wide this block spans.",
                "required": False,
            },
        ),
        9: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                "help_text": "Horizontal alignment within the page.",
                "required": False,
            },
        ),
        10: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("top", "Top"), ("centre", "Centre"), ("bottom", "Bottom")],
                "help_text": "Vertical alignment within a column layout.",
                "required": False,
            },
        ),
        11: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                "help_text": "Background color for this block.",
                "required": False,
            },
        ),
        12: (
            "wagtail.blocks.BooleanBlock",
            (),
            {
                "default": False,
                "help_text": "Stretch the background to the full width of the page.",
                "required": False,
            },
        ),
        13: (
            "wagtail.blocks.StructBlock",
            [
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 2),
                    ("image_link_page", 3),
                    ("image_link_url", 4),
                    ("image_width", 5),
                    ("image_style", 6),
                    ("image_alignment", 7),
                    ("width", 8),
                    ("alignment", 9),
                    ("vertical_alignment", 10),
                    ("background_color", 11),
                    ("full_width_background", 12),
                ]
            ],
            {},
        ),
        14: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
        15: (
            "wagtail.blocks.StructBlock",
            [
                [
                    ("image", 14),
                    ("image_link_page", 3),
                    ("image_link_url", 4),
                    ("image_width", 5),
                    ("image_style", 6),
                    ("width", 8),
                    ("alignment", 9),
                    ("vertical_alignment", 10),
                    ("background_color", 11),
                    ("full_width_background", 12),
                ]
            ],
            {},
        ),
        16: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
        17: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Content revealed when expanded", "required": True}),
        18: ("wagtail.blocks.StructBlock", [[("title", 16), ("content", 17)]], {}),
        19: ("wagtail.blocks.ListBlock", (18,), {}),
        20: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                "help_text": "Background color for accordion headers.",
                "required": False,
            },
        ),
        21: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                "help_text": "Background color for accordion content panels.",
                "required": False,
            },
        ),
        22: (
            "wagtail.blocks.StructBlock",
            [
                [
                    ("items", 19),
                    ("header_color", 20),
                    ("content_color", 21),
                    ("width", 8),
                    ("alignment", 9),
                    ("vertical_alignment", 10),
                    ("background_color", 11),
                    ("full_width_background", 12),
                ]
            ],
            {},
        ),
        23: (
            "wagtail.embeds.blocks.EmbedBlock",
            (),
            {"help_text": "Paste a URL to embed (YouTube, Vimeo, Spotify, etc.)."},
        ),
        24: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional caption below the embed.", "required": False}),
        25: (
            "wagtail.blocks.StructBlock",
            [
                [
                    ("url", 23),
                    ("caption", 24),
                    ("width", 8),
                    ("alignment", 9),
                    ("vertical_alignment", 10),
                    ("background_color", 11),
                    ("full_width_background", 12),
                ]
            ],
            {},
        ),
        26: ("wagtail.blocks.TextBlock", (), {"help_text": "The quote text.", "required": True}),
        27: (
            "wagtail.blocks.CharBlock",
            (),
            {"help_text": "Optional attribution (e.g., author name).", "required": False},
        ),
        28: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("default", "Default"), ("small", "Small"), ("large", "Large")],
                "help_text": "Font size for this block.",
                "required": False,
            },
        ),
        29: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("normal", "Normal"), ("bold", "Bold")],
                "help_text": "Font weight for this block.",
                "required": False,
            },
        ),
        30: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("italic", "Italic"), ("normal", "Normal")],
                "help_text": "Font style for this block.",
                "required": False,
            },
        ),
        31: (
            "wagtail.blocks.StructBlock",
            [
                [
                    ("quote", 26),
                    ("attribution", 27),
                    ("font_size", 28),
                    ("font_weight", 29),
                    ("font_style", 30),
                    ("width", 8),
                    ("alignment", 9),
                    ("vertical_alignment", 10),
                    ("background_color", 11),
                    ("full_width_background", 12),
                ]
            ],
            {},
        ),
        32: ("wagtail.blocks.RawHTMLBlock", (), {}),
        33: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [
                    ("bash", "Bash/Shell"),
                    ("css", "CSS"),
                    ("diff", "diff"),
                    ("html", "HTML"),
                    ("javascript", "Javascript"),
                    ("json", "JSON"),
                    ("python", "Python"),
                    ("scss", "SCSS"),
                    ("yaml", "YAML"),
                ],
                "help_text": "Coding language",
                "identifier": "language",
                "label": "Language",
            },
        ),
        34: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
        35: ("wagtail.blocks.StructBlock", [[("language", 33), ("code", 34)]], {"label": "Code"}),
        36: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [
                    ("1-1", "Two columns (50 / 50)"),
                    ("1-2", "Two columns (33 / 67)"),
                    ("2-1", "Two columns (67 / 33)"),
                    ("1-1-1", "Three columns (33 / 33 / 33)"),
                    ("1-1-1-1", "Four columns (25 / 25 / 25 / 25)"),
                    ("1-2-1", "Three columns (25 / 50 / 25)"),
                ],
                "help_text": "Choose a column layout for this row.",
            },
        ),
        37: (
            "wagtail.blocks.StreamBlock",
            [
                [
                    ("content_block", 13),
                    ("image", 15),
                    ("accordion", 22),
                    ("embed", 25),
                    ("blockquote", 31),
                    ("raw_html", 32),
                    ("code", 35),
                ]
            ],
            {},
        ),
        38: (
            "wagtail.blocks.BooleanBlock",
            (),
            {"default": False, "help_text": "Stretch text content to fill the full column height.", "required": False},
        ),
        39: ("wagtail.blocks.StructBlock", [[("content", 37), ("stretch", 38), ("background_color", 11)]], {}),
        40: ("wagtail.blocks.ListBlock", (39,), {"max_num": 4, "min_num": 1}),
        41: (
            "wagtail.blocks.StructBlock",
            [[("layout", 36), ("columns", 40), ("background_color", 11), ("full_width_background", 12)]],
            {},
        ),
        42: ("wagtail.blocks.CharBlock", (), {"help_text": "Title of the documentation panel", "required": True}),
        43: (
            "wagtail.blocks.CharBlock",
            (),
            {"help_text": "Unique identifier in the url e.g. workflow", "max_length": 50, "required": True},
        ),
        44: (
            "wagtail.blocks.RichTextBlock",
            (),
            {"help_text": "Description of the documentation panel", "required": True},
        ),
        45: (
            "wagtail.images.blocks.ImageChooserBlock",
            (),
            {"help_text": "Optional image for the documentation panel", "required": False},
        ),
        46: (
            "wagtail.blocks.BooleanBlock",
            (),
            {
                "default": False,
                "help_text": "Use the image as a full card background with the title overlaid",
                "required": False,
            },
        ),
        47: (
            "wagtail.blocks.StructBlock",
            [[("title", 42), ("slug", 43), ("description", 44), ("image", 45), ("featured_image", 46)]],
            {},
        ),
        48: ("wagtail.blocks.ListBlock", (47,), {"label": "Topic cards"}),
        49: (
            "wagtail.blocks.StructBlock",
            [[("topics", 48), ("background_color", 11), ("full_width_background", 12)]],
            {},
        ),
    },
)


def _alter_body(model_name):
    return migrations.AlterField(model_name=model_name, name="body", field=_BODY_FIELD.clone())


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_alter_aboutindexpage_body_alter_casestudiespage_body_and_more"),
    ]

    operations = [
        # 1. Register topics_grid on every body StreamField first so the
        #    historical model's stream_block can validate the new block.
        _alter_body("aboutindexpage"),
        _alter_body("casestudiespage"),
        _alter_body("catalogueindexpage"),
        _alter_body("dataindexpage"),
        _alter_body("docsindexpage"),
        _alter_body("genericpage"),
        # 2. Move data (live + revisions) before fields are dropped.
        migrations.RunPython(migrate_topics_into_body, migrations.RunPython.noop),
        # 3. Drop the now-empty fields.
        migrations.RemoveField(model_name="aboutindexpage", name="topics"),
        migrations.RemoveField(model_name="aboutindexpage", name="topics_background_color"),
        migrations.RemoveField(model_name="aboutindexpage", name="topics_full_width_background"),
        migrations.RemoveField(model_name="casestudiespage", name="topics"),
        migrations.RemoveField(model_name="casestudiespage", name="topics_background_color"),
        migrations.RemoveField(model_name="casestudiespage", name="topics_full_width_background"),
        migrations.RemoveField(model_name="catalogueindexpage", name="topics"),
        migrations.RemoveField(model_name="catalogueindexpage", name="topics_background_color"),
        migrations.RemoveField(model_name="catalogueindexpage", name="topics_full_width_background"),
        migrations.RemoveField(model_name="dataindexpage", name="topics"),
        migrations.RemoveField(model_name="dataindexpage", name="topics_background_color"),
        migrations.RemoveField(model_name="dataindexpage", name="topics_full_width_background"),
        migrations.RemoveField(model_name="docsindexpage", name="topics"),
        migrations.RemoveField(model_name="docsindexpage", name="topics_background_color"),
        migrations.RemoveField(model_name="docsindexpage", name="topics_full_width_background"),
        migrations.RemoveField(model_name="genericpage", name="topics"),
        migrations.RemoveField(model_name="genericpage", name="topics_background_color"),
        migrations.RemoveField(model_name="genericpage", name="topics_full_width_background"),
    ]
