# Generated by Django 6.0.4 on 2026-04-21 17:04
#
# Merge the old per-page CTA fields (cta_text, cta_url) into body
# as a new cta block so editors can reorder CTA buttons freely.
#
# One-way migration: reverse cannot faithfully reconstruct the old
# single-CTA layout once editors add or move cta blocks. Snapshot
# the DB before applying in prod.

import json
import uuid

import wagtail.fields
from django.db import migrations
from django.db.models import F, JSONField
from django.db.models.functions import Cast
from wagtail.blocks import StreamValue


def _wrap_cta_as_block(cta_text, cta_url):
    if not cta_text or not cta_url:
        return None
    return {
        "type": "cta",
        "value": {
            "text": cta_text,
            "link_page": None,
            "link_url": cta_url,
            "button_style": "primary",
            "width": "default",
            "alignment": "none",
            "vertical_alignment": "top",
            "background_color": "default",
            "full_width_background": False,
        },
        "id": str(uuid.uuid4()),
    }


def migrate_cta_into_body(apps, schema_editor):
    Revision = apps.get_model("wagtailcore", "Revision")
    ContentType = apps.get_model("contenttypes", "ContentType")

    Model = apps.get_model("home", "genericpage")
    ct = ContentType.objects.get_for_model(Model)
    body_stream_block = Model._meta.get_field("body").stream_block

    # Live/draft rows
    queryset = Model.objects.annotate(
        raw_body=Cast(F("body"), JSONField()),
    )

    updates = []
    for page in queryset.iterator(chunk_size=512):
        cta_text = page.cta_text
        cta_url = page.cta_url
        block = _wrap_cta_as_block(cta_text, cta_url)
        if block is None:
            continue
        body_raw = list(page.raw_body or [])
        body_raw.append(block)
        page.body = StreamValue(body_stream_block, body_raw, is_lazy=True)
        updates.append(page)
        if len(updates) >= 512:
            Model.objects.bulk_update(updates, ["body"])
            updates = []
    if updates:
        Model.objects.bulk_update(updates, ["body"])

    # Revisions
    for revision in Revision.objects.filter(content_type_id=ct.id).iterator(chunk_size=512):
        content = revision.content
        body_json = content.get("body") or "[]"
        cta_text = content.get("cta_text", "")
        cta_url = content.get("cta_url", "")
        block = _wrap_cta_as_block(cta_text, cta_url)
        if block is None:
            continue
        body_raw = json.loads(body_json) if body_json else []
        body_raw.append(block)
        content["body"] = json.dumps(body_raw)
        # Zero the old fields so a revision restore doesn't resurrect them.
        content.pop("cta_text", None)
        content.pop("cta_url", None)
        revision.content = content
        revision.save(update_fields=["content"])


_BODY_FIELD = wagtail.fields.StreamField(
    [
        ("content_block", 15),
        ("image", 17),
        ("accordion", 24),
        ("embed", 27),
        ("blockquote", 33),
        ("raw_html", 34),
        ("code", 37),
        ("cta", 42),
        ("columns", 48),
        ("topics_grid", 56),
    ],
    blank=True,
    block_lookup={
        0: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional heading", "required": False}),
        1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
        2: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
        3: (
            "home.blocks.IconPickerBlock",
            (),
            {
                "help_text": "Click the Pick icon button to browse available icons.",
                "max_length": 100,
                "required": False,
            },
        ),
        4: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("sm", "SM"), ("md", "MD"), ("lg", "LG"), ("xl", "XL")],
                "help_text": "Icon size.",
                "required": False,
            },
        ),
        5: (
            "wagtail.blocks.PageChooserBlock",
            (),
            {"help_text": "Link the image to an internal page.", "required": False},
        ),
        6: (
            "wagtail.blocks.URLBlock",
            (),
            {
                "help_text": "Link the image to an external URL. Page link takes priority if both are set.",
                "required": False,
            },
        ),
        7: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [
                    ("100", "Original dimensions (100%)"),
                    ("75", "75% of original dimensions"),
                    ("50", "50% of original dimensions"),
                    ("25", "25% of original dimensions"),
                ],
                "help_text": "Display width as a percentage of the image's original dimensions.",
                "required": False,
            },
        ),
        8: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("rounded", "Rounded corners"), ("square", "Square corners"), ("pill", "Pill / circular")],
                "help_text": "Visual style for the image.",
                "required": False,
            },
        ),
        9: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                "help_text": "Horizontal alignment of the image within the block.",
                "required": False,
            },
        ),
        10: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("default", "Default"), ("medium", "Medium"), ("small", "Small")],
                "help_text": "Control how wide this block spans.",
                "required": False,
            },
        ),
        11: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("none", "None"), ("left", "Left"), ("centre", "Centre"), ("right", "Right")],
                "help_text": "Horizontal alignment within the page.",
                "required": False,
            },
        ),
        12: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("top", "Top"), ("centre", "Centre"), ("bottom", "Bottom")],
                "help_text": "Vertical alignment within a column layout.",
                "required": False,
            },
        ),
        13: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                "help_text": "Background color for this block.",
                "required": False,
            },
        ),
        14: (
            "wagtail.blocks.BooleanBlock",
            (),
            {
                "default": False,
                "help_text": "Stretch the background to the full width of the page.",
                "required": False,
            },
        ),
        15: (
            "wagtail.blocks.StructBlock",
            [
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 2),
                    ("icon_name", 3),
                    ("icon_size", 4),
                    ("image_link_page", 5),
                    ("image_link_url", 6),
                    ("image_width", 7),
                    ("image_style", 8),
                    ("image_alignment", 9),
                    ("width", 10),
                    ("alignment", 11),
                    ("vertical_alignment", 12),
                    ("background_color", 13),
                    ("full_width_background", 14),
                ]
            ],
            {},
        ),
        16: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
        17: (
            "wagtail.blocks.StructBlock",
            [
                [
                    ("image", 16),
                    ("image_link_page", 5),
                    ("image_link_url", 6),
                    ("image_width", 7),
                    ("image_style", 8),
                    ("width", 10),
                    ("alignment", 11),
                    ("vertical_alignment", 12),
                    ("background_color", 13),
                    ("full_width_background", 14),
                ]
            ],
            {},
        ),
        18: ("wagtail.blocks.CharBlock", (), {"help_text": "Accordion item heading", "required": True}),
        19: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Content revealed when expanded", "required": True}),
        20: ("wagtail.blocks.StructBlock", [[("title", 18), ("content", 19), ("icon_name", 3), ("icon_size", 4)]], {}),
        21: ("wagtail.blocks.ListBlock", (20,), {}),
        22: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                "help_text": "Background color for accordion headers.",
                "required": False,
            },
        ),
        23: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [
                    ("default", "Default (theme)"),
                    ("nceo-purple", "NCEO Purple"),
                    ("navy", "Navy"),
                    ("light-grey", "Light Grey"),
                    ("steel", "Steel"),
                    ("blue", "Blue"),
                ],
                "help_text": "Background color for accordion content panels.",
                "required": False,
            },
        ),
        24: (
            "wagtail.blocks.StructBlock",
            [
                [
                    ("items", 21),
                    ("header_color", 22),
                    ("content_color", 23),
                    ("width", 10),
                    ("alignment", 11),
                    ("vertical_alignment", 12),
                    ("background_color", 13),
                    ("full_width_background", 14),
                ]
            ],
            {},
        ),
        25: (
            "wagtail.embeds.blocks.EmbedBlock",
            (),
            {"help_text": "Paste a URL to embed (YouTube, Vimeo, Spotify, etc.)."},
        ),
        26: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional caption below the embed.", "required": False}),
        27: (
            "wagtail.blocks.StructBlock",
            [
                [
                    ("url", 25),
                    ("caption", 26),
                    ("width", 10),
                    ("alignment", 11),
                    ("vertical_alignment", 12),
                    ("background_color", 13),
                    ("full_width_background", 14),
                ]
            ],
            {},
        ),
        28: ("wagtail.blocks.TextBlock", (), {"help_text": "The quote text.", "required": True}),
        29: (
            "wagtail.blocks.CharBlock",
            (),
            {"help_text": "Optional attribution (e.g., author name).", "required": False},
        ),
        30: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("default", "Default"), ("small", "Small"), ("large", "Large")],
                "help_text": "Font size for this block.",
                "required": False,
            },
        ),
        31: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("normal", "Normal"), ("bold", "Bold")],
                "help_text": "Font weight for this block.",
                "required": False,
            },
        ),
        32: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("italic", "Italic"), ("normal", "Normal")],
                "help_text": "Font style for this block.",
                "required": False,
            },
        ),
        33: (
            "wagtail.blocks.StructBlock",
            [
                [
                    ("quote", 28),
                    ("attribution", 29),
                    ("icon_name", 3),
                    ("icon_size", 4),
                    ("font_size", 30),
                    ("font_weight", 31),
                    ("font_style", 32),
                    ("width", 10),
                    ("alignment", 11),
                    ("vertical_alignment", 12),
                    ("background_color", 13),
                    ("full_width_background", 14),
                ]
            ],
            {},
        ),
        34: ("wagtail.blocks.RawHTMLBlock", (), {}),
        35: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [
                    ("bash", "Bash/Shell"),
                    ("css", "CSS"),
                    ("diff", "diff"),
                    ("html", "HTML"),
                    ("javascript", "Javascript"),
                    ("json", "JSON"),
                    ("python", "Python"),
                    ("scss", "SCSS"),
                    ("yaml", "YAML"),
                ],
                "help_text": "Coding language",
                "identifier": "language",
                "label": "Language",
            },
        ),
        36: ("wagtail.blocks.TextBlock", (), {"identifier": "code", "label": "Code"}),
        37: ("wagtail.blocks.StructBlock", [[("language", 35), ("code", 36)]], {"label": "Code"}),
        38: ("wagtail.blocks.CharBlock", (), {"help_text": "Button label text", "required": True}),
        39: (
            "wagtail.blocks.PageChooserBlock",
            (),
            {
                "help_text": "Link to an internal page. Takes priority over the URL field if both are set.",
                "required": False,
            },
        ),
        40: ("wagtail.blocks.URLBlock", (), {"help_text": "Link to an external URL.", "required": False}),
        41: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [("primary", "Primary"), ("secondary", "Secondary")],
                "help_text": "Visual style for the button.",
                "required": False,
            },
        ),
        42: (
            "wagtail.blocks.StructBlock",
            [
                [
                    ("text", 38),
                    ("link_page", 39),
                    ("link_url", 40),
                    ("button_style", 41),
                    ("width", 10),
                    ("alignment", 11),
                    ("vertical_alignment", 12),
                    ("background_color", 13),
                    ("full_width_background", 14),
                ]
            ],
            {},
        ),
        43: (
            "wagtail.blocks.ChoiceBlock",
            [],
            {
                "choices": [
                    ("1-1", "Two columns (50 / 50)"),
                    ("1-2", "Two columns (33 / 67)"),
                    ("2-1", "Two columns (67 / 33)"),
                    ("1-1-1", "Three columns (33 / 33 / 33)"),
                    ("1-1-1-1", "Four columns (25 / 25 / 25 / 25)"),
                    ("1-2-1", "Three columns (25 / 50 / 25)"),
                ],
                "help_text": "Choose a column layout for this row.",
            },
        ),
        44: (
            "wagtail.blocks.StreamBlock",
            [
                [
                    ("content_block", 15),
                    ("image", 17),
                    ("accordion", 24),
                    ("embed", 27),
                    ("blockquote", 33),
                    ("raw_html", 34),
                    ("code", 37),
                    ("cta", 42),
                ]
            ],
            {},
        ),
        45: (
            "wagtail.blocks.BooleanBlock",
            (),
            {"default": False, "help_text": "Stretch text content to fill the full column height.", "required": False},
        ),
        46: ("wagtail.blocks.StructBlock", [[("content", 44), ("stretch", 45), ("background_color", 13)]], {}),
        47: ("wagtail.blocks.ListBlock", (46,), {"max_num": 4, "min_num": 1}),
        48: (
            "wagtail.blocks.StructBlock",
            [[("layout", 43), ("columns", 47), ("background_color", 13), ("full_width_background", 14)]],
            {},
        ),
        49: ("wagtail.blocks.CharBlock", (), {"help_text": "Title of the documentation panel", "required": True}),
        50: (
            "wagtail.blocks.CharBlock",
            (),
            {"help_text": "Unique identifier in the url e.g. workflow", "max_length": 50, "required": True},
        ),
        51: (
            "wagtail.blocks.RichTextBlock",
            (),
            {"help_text": "Description of the documentation panel", "required": True},
        ),
        52: (
            "wagtail.images.blocks.ImageChooserBlock",
            (),
            {"help_text": "Optional image for the documentation panel", "required": False},
        ),
        53: (
            "wagtail.blocks.BooleanBlock",
            (),
            {
                "default": False,
                "help_text": "Use the image as a full card background with the title overlaid",
                "required": False,
            },
        ),
        54: (
            "wagtail.blocks.StructBlock",
            [
                [
                    ("title", 49),
                    ("slug", 50),
                    ("description", 51),
                    ("image", 52),
                    ("featured_image", 53),
                    ("icon_name", 3),
                    ("icon_size", 4),
                ]
            ],
            {},
        ),
        55: ("wagtail.blocks.ListBlock", (54,), {"label": "Topic cards"}),
        56: (
            "wagtail.blocks.StructBlock",
            [[("topics", 55), ("background_color", 13), ("full_width_background", 14)]],
            {},
        ),
    },
)


def _alter_body(model_name):
    return migrations.AlterField(model_name=model_name, name="body", field=_BODY_FIELD.clone())


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_alter_aboutindexpage_body_alter_casestudiespage_body_and_more"),
    ]

    operations = [
        # 1. Register cta on every body StreamField first so the
        #    historical model's stream_block can validate the new block.
        _alter_body("aboutindexpage"),
        _alter_body("casestudiespage"),
        _alter_body("catalogueindexpage"),
        _alter_body("dataindexpage"),
        _alter_body("docsindexpage"),
        _alter_body("genericpage"),
        # 2. Move data (live + revisions) before fields are dropped.
        migrations.RunPython(migrate_cta_into_body, migrations.RunPython.noop),
        # 3. Drop the now-empty fields.
        migrations.RemoveField(model_name="genericpage", name="cta_text"),
        migrations.RemoveField(model_name="genericpage", name="cta_url"),
    ]
