# Generated by Django 6.0.4 on 2026-04-21 17:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_cta_to_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentationpage",
            name="topics",
            field=wagtail.fields.StreamField(
                [("documentation_panel", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title of the documentation panel", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Unique identifier in the url e.g. workflow",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Description of the documentation panel", "required": True},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional image for the documentation panel", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Use the image as a full card background with the title overlaid",
                            "required": False,
                        },
                    ),
                    5: (
                        "home.blocks.IconPickerBlock",
                        (),
                        {
                            "help_text": "Click the Pick icon button to browse available icons.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("sm", "SM"), ("md", "MD"), ("lg", "LG"), ("xl", "XL")],
                            "help_text": "Icon size.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("slug", 1),
                                ("description", 2),
                                ("image", 3),
                                ("featured_image", 4),
                                ("icon_name", 5),
                                ("icon_size", 6),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Add documentation panels to this page.",
            ),
        ),
    ]
