# Generated by Django 6.0.4 on 2026-04-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_label_documentationpage_topics_show_filter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutindexpage",
            name="hero_caption",
            field=models.TextField(
                blank=True, help_text="Caption or alt-text for the hero image. Press Enter for a new line."
            ),
        ),
        migrations.AlterField(
            model_name="casestudiespage",
            name="hero_caption",
            field=models.TextField(
                blank=True, help_text="Caption or alt-text for the hero image. Press Enter for a new line."
            ),
        ),
        migrations.AlterField(
            model_name="catalogueindexpage",
            name="hero_caption",
            field=models.TextField(
                blank=True, help_text="Caption or alt-text for the hero image. Press Enter for a new line."
            ),
        ),
        migrations.AlterField(
            model_name="dataindexpage",
            name="hero_caption",
            field=models.TextField(
                blank=True, help_text="Caption or alt-text for the hero image. Press Enter for a new line."
            ),
        ),
        migrations.AlterField(
            model_name="docsindexpage",
            name="hero_caption",
            field=models.TextField(
                blank=True, help_text="Caption or alt-text for the hero image. Press Enter for a new line."
            ),
        ),
        migrations.AlterField(
            model_name="genericpage",
            name="hero_caption",
            field=models.TextField(
                blank=True, help_text="Caption or alt-text for the hero image. Press Enter for a new line."
            ),
        ),
    ]
