# Generated by Django 6.0.4 on 2026-05-11 12:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_aboutindexpage_hero_caption_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Short optional label, e.g. 'Maintenance'", max_length=100)),
                ('message', wagtail.fields.RichTextField(help_text='Banner message content (basic formatting and links only)')),
                ('status', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('link_text', models.CharField(blank=True, help_text='Optional CTA text', max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='Optional external URL')),
                ('starts_at', models.DateTimeField(blank=True, help_text='When the banner should start showing. Times are stored in UTC.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='When the banner should stop showing. Times are stored in UTC.', null=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable or disable this banner')),
                ('priority', models.IntegerField(default=0, help_text='Higher values win when multiple banners are active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_page', models.ForeignKey(blank=True, help_text='Optional internal Wagtail page link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['-priority', 'starts_at', 'title'],
            },
        ),
    ]
