# Generated by Django 6.0.5 on 2026-05-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_notificationbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericpage',
            name='back_button_location',
        ),
    ]
