# Generated by Django 6.0.5 on 2026-06-15 08:13

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_genericpage_back_button_location'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('summary_override', models.CharField(blank=True, help_text="Optional summary; defaults to the case study's intro text.", max_length=300)),
                ('case_study', models.ForeignKey(help_text='A case study page (a page under the Case Studies section).', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
                ('image_override', models.ForeignKey(blank=True, help_text="Optional image; defaults to the case study's hero image.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('label', models.ForeignKey(blank=True, help_text='Optional sector badge shown on the slide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.label')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_case_studies', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, help_text='Optional credit or caption shown on the slide.', max_length=200)),
                ('image', models.ForeignKey(help_text='Background image for the hero carousel.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_images', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
