name: All checks
on:
  push:
    tags:
      - 'v[0-9]+'
      - 'v[0-9]+-*'
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+-*'
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
    branches:
      - '**'
  pull_request: ~

jobs:
  qa-python:
    uses: EO-DataHub/github-actions/.github/workflows/qa-python.yaml@main

  qa-frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Install frontend dependencies
        run: npm ci

      - name: Lint and format JavaScript
        run: npm run lint

      # Uncomment when all warnings are fixed
      # - name: Lint and format styles
      #   run: npm run lint:css

      - name: Build frontend assets
        env:
          GIT_REF_NAME: ${{ github.ref_name }}
          GIT_SHA: ${{ github.sha }}
        run: |
          npm run build:icons
          npm run build

  security-scan:
    name: Call Security Scan
    uses: EO-DataHub/github-actions/.github/workflows/security.yaml@main

  unit-tests:
    name: Run unit tests
    needs: qa-python
    uses: EO-DataHub/github-actions/.github/workflows/unit-tests-python-uv.yaml@main

  publish:
    name: Build and push Docker image
    needs: [qa-frontend, unit-tests]
    uses: EO-DataHub/github-actions/.github/workflows/ecr-publish.yaml@main
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      aws_role_arn: ${{ vars.AWS_ROLE_ARN }}
      aws_ecr_alias: ${{ vars.AWS_ECR_ALIAS }}
    permissions:
      id-token: write
      contents: read
