name: All checks
on:
  pull_request:
  workflow_call:

jobs:
  pre-commit:
    name: Pre-commit
    uses: EO-DataHub/github-actions/.github/workflows/pre-commit.yaml@main
  security-scan:
    name: Call Security Scan
    uses: EO-DataHub/github-actions/.github/workflows/security.yaml@main
