name: All checks
on:
  pull_request:
  workflow_call:

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: EO-DataHub/github-actions
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install pre-commit
        run: pip install pre-commit
      - run: ls
#      - name: Collect config file
#        run: cp .pre-commit-config.yaml .pre-commit-config.yaml
      - name: Install pre-commit hooks
        run: pre-commit install --install-hooks
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
  security-scan:
    name: Call Security Scan
    uses: EO-DataHub/github-actions/.github/workflows/security.yaml@main
