name: All checks
on:
  pull_request:
  workflow_call:
  push:
    tags:
      - 'v[0-9]+'
      - 'v[0-9]+-*'
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+-*'
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
    branches:
      - '**'

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: repository

      - uses: actions/checkout@v3
        with:
          repository: EO-DataHub/github-actions
          ref: main
          path: pre-commit

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Copy config
        run: curl -o repository/.pre-commit-config.yaml https://raw.githubusercontent.com/EO-DataHub/github-actions/main/.pre-commit-config-python.yaml

      - name: Run pre-commit hooks
        run: |
          cd repository
          pre-commit install --install-hooks
          pre-commit run --all-files

  security-scan:
    name: Call Security Scan
    uses: EO-DataHub/github-actions/.github/workflows/security.yaml@main

  get-tag-name:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get-image-tag.outputs.image_tag }}
    steps:
      - name: Get image tag
        id: get-image-tag
        run: echo IMAGE_TAG=$(if [[ "${GITHUB_REF##refs/tags/}" =~ ^v ]]; then echo ${GITHUB_REF##refs/tags/v}; elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then echo "latest"; else echo "${GITHUB_REF##refs/heads/}-latest" | sed "s/[^a-zA-Z0-9]/-/g" ; fi) >> "$GITHUB_ENV"

  aws-ecr-build:
    name: Build ECR image
    uses: EO-DataHub/github-actions/.github/workflows/docker-image-to-aws-ecr.yaml@main
    with:
      image_name: eodhp-web-presence
      image_tag: ${{ needs.get-tag-name.outputs.image_tag }}
    permissions:
      id-token: write
      contents: read
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ECR: ${{ secrets.AWS_ECR }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
