name: All checks
on:
  pull_request:
  workflow_call:

jobs:
  call-super-linter:

    name: Call Super-Linter

    permissions:
      contents: read # clone the repo to lint
      statuses: write # read/write to repo custom statuses

    ### use Reusable Workflows to call my workflow remotely
    ### https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
    ### you can also call workflows from inside the same repo via file path

    uses: EO-DataHub/github-actions/.github/workflows/security.yaml@main

    ### Optional settings examples

    # with:
      ### For a DevOps-focused repository. Prevents some code-language linters from running
      ### defaults to false
      # devops-only: false

      ### A regex to exclude files from linting
      ### defaults to empty
      # filter-regex-exclude: html/.*
#jobs:
#  build:
#    name: Check for vulnerabilities
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Pre-commit
#        uses: EO-DataHub/github-actions/.github/workflows/pre-commit.yaml
#
#      - name: Security check - Bandit
#        uses: mdegis/bandit-action@v1.0.1
#        with:
#          path: "."
#          level: high
#          confidence: high
#          skips: B101
#
#      - name: Security check - Trivy
#        uses: aquasecurity/trivy-action@0.24.0
#        with:
#          scan-type: 'fs'
#          scan-ref: '.'
#          severity: 'MEDIUM,CRITICAL,HIGH'
#          exit-code: '1'
#          trivy-config: |
#            rules:
#              - id: rule1
#                category: general
#                title: Generic Rule
#                severity: 'MEDIUM,CRITICAL,HIGH'
#                keywords:
#                  - secret
#                regex: (?i)(?P<key>(secret))(=|:).{0,5}'\"['\"]
#                secret-group-name: secret

#  pre-commit:
#    name: Pre-commit
#    uses: EO-DataHub/github-actions/.github/workflows/pre-commit.yaml@main

#  security-scan:
##    uses: EO-DataHub/github-actions/.github/workflows/security.yaml@main
#
#    uses:  bretfisher/super-linter-workflow/.github/workflows/reusable-super-linter.yaml@main
#

#jobs:
#
