name: All checks
on:
  pull_request:
  workflow_call:

jobs:
  security-scan:

    name: Call Security Scan
    permissions:
      contents: read
    uses: EO-DataHub/github-actions/.github/workflows/security.yaml@main


#  pre-commit:
#    name: Pre-commit
#    uses: EO-DataHub/github-actions/.github/workflows/pre-commit.yaml@main

#  security-scan:
##    uses: EO-DataHub/github-actions/.github/workflows/security.yaml@main
#
#    uses:  bretfisher/super-linter-workflow/.github/workflows/reusable-super-linter.yaml@main
#

#jobs:
#
