name: All checks
on:
  pull_request:
  workflow_call:

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Copy config
        run: curl -o .pre-commit-config.yaml https://raw.githubusercontent.com/EO-DataHub/github-actions/main/.pre-commit-config-python.yaml

      - name: Run pre-commit hooks
        run: |
          pre-commit install --install-hooks
          pre-commit run --all-files

  security-scan:
    name: Call Security Scan
    uses: EO-DataHub/github-actions/.github/workflows/security.yaml@main
