name: Security scan
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Check for vulnerabilities
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Security check - Bandit
        uses: ioggstream/bandit-report-artifacts@v0.0.2
        with:
          project_path: .
          ignore_failure: true
          skips: B101
          level: high
          confidence: high
