name: Security scan
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Check for vulnerabilities
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Security check - Bandit
        uses: mdegis/bandit-action@v1.0.1
        with:
          path: "."
          level: high
          confidence: high
          exit_zero: true
          skips: B101
