name: Security scan
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Security check - Bandit
        uses: ioggstream/bandit-report-artifacts@v0.0.2
        with:
          project_path: .
          ignore_failure: true
      - name: Bandit scan
        uses: mdegis/bandit-action@v1
        with:
          path: "."
          level: high
          confidence: high
          exit_zero: true
          skips: B101
