name: Unit tests

on:
  pull_request:
  workflow_call:

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: |
          uv sync
          npm ci

      - name: Check for missing migrations
        run: uv run python ./eodhp_web_presence/manage.py makemigrations --check

      - name: Build
        run: |
          npm run build
          uv run python ./eodhp_web_presence/manage.py collectstatic
          uv run python ./eodhp_web_presence/manage.py migrate

      - name: Run tests
        run: uv run pytest ./eodhp_web_presence -vv
